-- Fornecedor
CREATE TABLE Fornecedor(
	CNPJ NUMERIC(14) NOT NULL,
	RAZAO_SOCIAL VARCHAR(100),
	NOME_FANTASIA VARCHAR(25)
	);

--PK Fornecedor
ALTER TABLE Fornecedor ADD CONSTRAINT Fornecedor_pk PRIMARY KEY (CNPJ);

--Equipamento
CREATE TABLE Equipamento(
	CODIGO_EQUIPAMEMTO INTEGER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	QUANTIDADE INTEGER NOT NULL,
	CNPJ_FORNECEDOR NUMERIC(14) NOT NULL
	);	

--PK Equipamento
ALTER TABLE Equipamento ADD CONSTRAINT Equipamento_pk PRIMARY KEY (CODIGO_EQUIPAMEMTO);

--FK Equipamento
ALTER TABLE Equipamento ADD CONSTRAINT Fornecedor_Equipamento_fk FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES Fornecedor (CNPJ);

--Peca
CREATE TABLE Peca(
	CODIGO_PECA INTEGER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	QUANTIDADE INTEGER NOT NULL,
	TIPO VARCHAR(15) NOT NULL,
	EQUIPAMEMTO VARCHAR(50) NOT NULL,
	FORNECEDOR VARCHAR(50) NOT NULL
	);

--PK PECA
ALTER TABLE Peca ADD CONSTRAINT Peca_pk PRIMARY KEY (CODIGO_PECA);

--FK Peca
ALTER TABLE Peca ADD CONSTRAINT Equipamento_peca_fk FOREIGN KEY (CODIGO_EQUIPAMEMTO) REFERENCES Equipamento (CODIGO_EQUIPAMEMTO);

--FK Peca
ALTER TABLE Peca ADD CONSTRAINT Fornecedor_peca_fk FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES Fornecedor (CNPJ);