-- Fornecedor
CREATE TABLE Fornecedor(
	CNPJ NUMERIC(14) NOT NULL,
	RAZAO_SOCIAL VARCHAR(100),
	NOME_FANTASIA VARCHAR(30)
	CIDADE VARCHAR(50),
	UF VARCHAR(2),
	CEP VARCHAR (8),
	RUA VARCHAR(150),
	BAIRRO VARCHAR (50),
	NUMERO INTEGER,
	TELEFONE_1 VARCHAR (20),
	TELEFONE_2 VARCHAR (20)
	);

--PK Fornecedor
ALTER TABLE Fornecedor ADD CONSTRAINT Fornecedor_pk PRIMARY KEY (CNPJ);

--Equipamento
CREATE TABLE Equipamento(
	CODIGO_EQUIPAMEMTO INTEGER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	QUANTIDADE INTEGER NOT NULL,
	CNPJFORNECEDOR NUMERIC(14) NOT NULL
	);	

--PK Equipamento
ALTER TABLE Equipamento ADD CONSTRAINT Equipamento_pk PRIMARY KEY (CODIGO_EQUIPAMEMTO);

--FK Equipamento
ALTER TABLE Equipamento ADD CONSTRAINT Fornecedor_Equipamento_fk FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES Fornecedor (CNPJ);

--Peca
CREATE TABLE Peca(
	CODIGO_PECA INTEGER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	QUANTIDADE INTEGER NOT NULL,
	TIPO VARCHAR(15) NOT NULL,
	CODIGO_EQUIPAMEMTO INTEGER NOT NULL,
	CNPJ_FORNECEDOR NUMERIC(14) NOT NULL
	);

--PK PECA
ALTER TABLE Peca ADD CONSTRAINT Peca_pk PRIMARY KEY (CODIGO_PECA);

--FK Peca
ALTER TABLE Peca ADD CONSTRAINT Equipamento_peca_fk FOREIGN KEY (CODIGO_EQUIPAMEMTO) REFERENCES Equipamento (CODIGO_EQUIPAMEMTO);

--FK Peca
ALTER TABLE Peca ADD CONSTRAINT Fornecedor_peca_fk FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES Fornecedor (CNPJ);

--Historico peça que saem
CREATE TABLE historico_peca(
	CODIGO_PECA INTEGER NOT NULL,
	QUANTIDADE INTEGER NOT NULL,
	DATA_SAIDA TIMESTAMP NOT NULL
);

--PK HISTORICO_PECA
ALTER TABLE historico_peca ADD CONSTRAINT historico_peca_pk PRIMARY KEY (DATA_SAIDA);